#!/usr/bin/env bash
# dev-worktree.sh — manage per-issue git worktrees + isolated compose stacks.
#
# Conventions (see docs/dev-bringup.md):
#   - Trunk worktree at /home/hermes/netbox-pyats stays on main; no feature work
#     happens there. Each issue gets its own worktree under ../netbox-pyats-wt/.
#   - One issue = one branch = one worktree. Branch name: <type>/<issue-id>-<slug>.
#   - Each worktree runs its own docker compose project (COMPOSE_PROJECT_NAME)
#     on a unique loopback port drawn from a small pool.
#
# Commands:
#   dev-worktree.sh add <issue-id> <type> <slug>
#       Create ../netbox-pyats-wt/<issue-id> on branch <type>/<issue-id>-<slug>
#       from main, write .env with a unique port, and print path + port.
#
#   dev-worktree.sh up
#       Run `docker compose -f docker-compose.dev.yml up -d` in the current
#       worktree (uses the worktree's .env for project name + port).
#
#   dev-worktree.sh remove <issue-id>
#       Run `docker compose down -v` in the worktree, then `git worktree remove`.
#       Use when the issue reaches a terminal state (done/cancelled).
#
# Port pool: 8001..8010 (10 ports). Scans ../netbox-pyats-wt/*/.dev-port for
# claimed ports. Fails loud if the pool is exhausted.

set -euo pipefail

# Resolve the trunk repo root (the worktree this script lives alongside, or the
# common dir for linked worktrees). We anchor everything to the trunk so the
# script works no matter which worktree it is invoked from.
TRUNK="$(git rev-parse --git-common-dir 2>/dev/null)"
if [ -z "$TRUNK" ]; then
  echo "error: not inside a git repo" >&2
  exit 1
fi
# git-common-dir is relative to cwd for main worktree, absolute for linked ones.
case "$TRUNK" in
  /*) TRUNK="$(cd "$TRUNK" && pwd)" ;;
  *)  TRUNK="$(cd "$(pwd)/$TRUNK" && pwd)" ;;
esac
# The trunk working tree is the parent of the .git dir for the main worktree.
TRUNK_ROOT="$(dirname "$TRUNK")"
# Worktrees live in a sibling directory of the trunk repo (not nested inside
# it), so e.g. /home/hermes/netbox-pyats -> /home/hermes/netbox-pyats-wt.
WT_ROOT="$(dirname "$TRUNK_ROOT")/$(basename "$TRUNK_ROOT")-wt"

PORT_MIN=8001
PORT_MAX=8010

die() { echo "error: $*" >&2; exit 1; }

next_free_port() {
  local claimed=""
  if [ -d "$WT_ROOT" ]; then
    claimed="$(find "$WT_ROOT" -maxdepth 2 -name '.dev-port' -exec cat {} \; 2>/dev/null || true)"
  fi
  local port="$PORT_MIN"
  while [ "$port" -le "$PORT_MAX" ]; do
    if ! printf '%s\n' "$claimed" | grep -qx "$port"; then
      echo "$port"
      return 0
    fi
    port=$((port + 1))
  done
  die "port pool exhausted ($PORT_MIN..$PORT_MAX). Remove stale worktrees with: $0 remove <issue-id>"
}

usage() {
  cat >&2 <<EOF
usage: dev-worktree.sh <command> [args]

  add <issue-id> <type> <slug>     create a worktree for an issue
  up                               bring up the compose stack in the current worktree
  remove <issue-id>                tear down the worktree + its compose stack

examples:
  dev-worktree.sh add atw-44 chore dev-worktree-helper
  dev-worktree.sh up
  dev-worktree.sh remove atw-44
EOF
  exit 2
}

cmd_add() {
  local issue_id="${1:-}" type="${2:-}" slug="${3:-}"
  [ -n "$issue_id" ] && [ -n "$type" ] && [ -n "$slug" ] || usage

  # Accept both short (feat) and long (feature) forms; normalise to short.
  case "$type" in
    feat|feature)   type=feat ;;
    fix)            type=fix ;;
    chore)          type=chore ;;
    docs)           type=docs ;;
    infra)          type=infra ;;
    refactor)       type=refactor ;;
    test)           type=test ;;
    *) die "type must be one of: feat fix chore docs infra refactor test (got '$type')" ;;
  esac

  local branch="$type/$issue_id-$slug"
  local wt="$WT_ROOT/$issue_id"

  [ -e "$wt" ] && die "worktree already exists: $wt"

  # Ensure the worktree directory exists.
  mkdir -p "$WT_ROOT"

  # Refuse to clobber an existing branch.
  if git show-ref --verify --quiet "refs/heads/$branch" 2>/dev/null; then
    die "branch already exists: $branch (delete it or pick a new slug)"
  fi

  local port
  port="$(next_free_port)"

  git -C "$TRUNK_ROOT" worktree add "$wt" -b "$branch" main

  # Record the claimed port and write the worktree .env so docker compose picks
  # up the project name + published port. COMPOSE_PROJECT_NAME namespaces
  # containers, volumes, and networks per issue.
  printf '%s\n' "$port" > "$wt/.dev-port"
  cat > "$wt/.env" <<EOF
# Per-worktree dev environment. Generated by scripts/dev-worktree.sh.
# Edit by hand if you need different resource caps; do not commit this file.
COMPOSE_PROJECT_NAME=$issue_id
NETBOX_PORT=$port
EOF

  cat <<EOF
created worktree: $wt
branch:          $branch
compose project: $issue_id
netbox port:     127.0.0.1:$port

Next:
  cd $wt
  scripts/dev-worktree.sh up
EOF
}

cmd_up() {
  # Run from the current worktree. Requires .env next to docker-compose.dev.yml.
  [ -f "./.env" ]           || die "no ./.env found — run this from a worktree created by 'dev-worktree.sh add'"
  [ -f "./docker-compose.dev.yml" ] || die "no ./docker-compose.dev.yml — run this from a worktree root"

  local port
  port="$(grep -E '^NETBOX_PORT=' .env | cut -d= -f2-)"
  echo "bringing up compose stack on 127.0.0.1:$port ..."
  docker compose -f docker-compose.dev.yml --env-file .env up -d
  echo
  echo "netbox: http://localhost:$port  (admin / admin)"
}

cmd_remove() {
  local issue_id="${1:-}"
  [ -n "$issue_id" ] || usage
  local wt="$WT_ROOT/$issue_id"

  [ -d "$wt" ] || die "no worktree for $issue_id at $wt"

  # Tear down the compose stack + volumes if the .env is still present.
  if [ -f "$wt/.env" ] && [ -f "$wt/docker-compose.dev.yml" ]; then
    echo "bringing down compose stack for $issue_id ..."
    docker compose -f "$wt/docker-compose.dev.yml" --env-file "$wt/.env" down -v \
      || echo "warning: compose down failed (continuing with worktree removal)" >&2
  else
    echo "no .env/compose file in $wt — skipping compose down"
  fi

  git -C "$TRUNK_ROOT" worktree remove --force "$wt"

  # Clean up the worktree directory if git left it behind.
  rmdir "$wt" 2>/dev/null || true

  # Delete the branch too. Refuse if it has unmerged commits; print the SHA so
  # the operator can recover it if they really meant to keep it.
  local branch
  branch="$(git -C "$TRUNK_ROOT" worktree list --porcelain 2>/dev/null \
            | awk -v wt="$wt/" 'BEGIN{found=0} /^worktree /{g=substr($2,1,length(wt)); if(g==wt) found=1; else found=0} found && /^branch /{print $2; exit}')"
  # The branch lookup above ran after removal, so it won't find anything. Track
  # branches by convention instead: <type>/<issue-id>-<slug>.
  echo "removed worktree: $wt"
  echo "note: matching branches (<type>/$issue_id-*) were not auto-deleted; remove with:"
  echo "  git -C \"$TRUNK_ROOT\" branch -D <branch>"
}

[ $# -ge 1 ] || usage
sub="$1"; shift
case "$sub" in
  add)    cmd_add "$@" ;;
  up)     cmd_up "$@" ;;
  remove) cmd_remove "$@" ;;
  -h|--help|help) usage ;;
  *)      usage ;;
esac